markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

collections:
  projects:
    output: true
    permalink: /:title
    dark: true
    light: false
    images: 0
    title: ""
    description: ""
    medium: ""
    year: ""
    end: 0

  links:
    output: false
    title: ""
    href: ""
    description: ""
    medium: ""
    year: ""
    end: 0

defaults:
  -
    scope:
      path: ""
    values:
      layout: "project"